project_id = "uzobpcqhwdreeltvdusc"

[functions.enhance-goal]
verify_jwt = true

[functions.enhance-letter]
verify_jwt = true

[functions.enhancement-status]
verify_jwt = false

[functions.suggest-milestones]
verify_jwt = true

[functions.trigger-letter-delivery]
verify_jwt = true
