// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzobpcqhwdreeltvdusc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6b2JwY3Fod2RyZWVsdHZkdXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODQyMDYsImV4cCI6MjA2OTY2MDIwNn0.RhUjApJ8Q7ysQIS-LvfO7vASVgNA_qcyx_jkTa4_ebY";

// Import the supabase client like this:
// import { supabase } from "@/shared/config/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
